 # scene.toml
 input       = "detnum_corner_z_x_y_r.txt"
 theta       = -120.0
 phi         = -25.0
 roll        = 85.0
 size        = "1920x1080"
 output      = "faust_renders/double_hit"
 color       = false
 transparent = false
 highlight_hits = true
hide_beam_downstream = true
 
[[track]]
theta = 2.0
phi   = -1.0
color = "red"

[[track]]
theta = 23.0
phi   = 43.0
rgb = [60, 0, 0]

[[track]]
theta = 12.0
phi   = -180.0
rgb = [60, 0, 0]

[[track]]
theta = 14.0
phi   = -180.0
rgb = [60, 0, 0]

