 # scene.toml
 input       = "detnum_corner_z_x_y_r.txt"
 theta       = -120.0
 phi         = -25.0
 roll        = 85.0
 size        = "3840x1600"
 output      = "faust_renders/real_2"
 color       = false
 transparent = false
 highlight_hits = true
hide_beam_downstream = true
 
[[track]]
theta = 4.3
phi   = 141.5
color = "red"
thickness = "thick"

[[track]]
theta = 29.8
phi   = -110.1
color = "red"
thickness = "thick"

[[track]]
theta = 12.0
phi   = 219.0
color = "red"
thickness = "thick"
